### ISSUE TITLE
allow for external AOT modules 

### ISSUE THREAD

**Issue by MrFrankel** [MrFrankel/share-loader#6] opened 2019-03-15 13:35 UTC
right now it is possible to load external modules when shell app is AOT, however it is required to import the JitCompiler manually and the external modules cant run in AOT.

it is possible to build the external modules in AOT and expose their AppModuleNgFactory to be consumed by the router, it is also required to stop the actual call to bootstrap as it is a feature module.

**Comment by dsuwirya** [comment] 2019-05-03 21:33
Hello,

None of the prod / AOT build for either `example-cli\ext-app1` or `example-cli\shell-app` seems to work, with the following errors:

![image](https://user-images.githubusercontent.com/5710527/57166725-a7549f00-6dc0-11e9-8f5b-fd584efc66bf.png)

![image](https://user-images.githubusercontent.com/5710527/57166758-c4896d80-6dc0-11e9-88a9-7a2c7f74397f.png)

Could you please give me pointer what do I do wrong ? Could you also please give more pointers how to make both ext-app1 and shell-app to be able to run in AOT?

Thanks.

**Comment by alexej-strelzow** [comment] 2019-05-23 16:29
This error is resolved fast - declare and export AppComponent in AppCommonModule = own NgModule and import it in the other ones.

To be able to build the app with AOT through custom build you need to pass --configuration=production, e.g. "build:prod": "ng run app1:build-prod --configuration=production".

But then it is more or less a dead end. I added the JiT Compiler ass in issue #5. Got an error that NgModule does not have meta data. And its true, the build-optimizer removes then. So build-optimizer: false in angular.json and then the next final problem:

![image](https://user-images.githubusercontent.com/16270237/58269854-b1970700-7d88-11e9-908d-7cce880a45ed.png)

and I'm really stuck here now. Mr Frankel, could you get it running?

**Comment by alexej-strelzow** [comment] 2019-05-23 20:16
I think loading aot bundles at runtime is not possible yet, see this question:
https://medium.com/@andreelrico/is-it-possible-with-this-approach-to-load-specific-modules-dynamically-at-run-time-623a54ebafa0 
answer 
https://medium.com/@andreelrico/is-it-possible-with-this-approach-to-load-specific-modules-dynamically-at-run-time-623a54ebafa0

regarding to this article: https://wesleygrimes.com/angular/2019/02/05/building-an-aot-friendly-dynamic-content-outlet.html

**Comment by MrFrankel** [comment] 2019-05-23 20:20
it's currently possible to load a JIT module into a AOT application at runtime as long as the compiler is provided in the ATP application.
It is also possible to load ATO module into a AOT application, but I have not yet gotten a chance to spec a full demo for it yet.

I've been really busy so i'm not sure when id get around to it, maybe next week somtime

**Comment by alexej-strelzow** [comment] 2019-05-24 09:46
Ok, thank you very much for sharing your knowledge! I'm very looking forward to your AOT solution.
Strangely I cannot run the composition layer with AOT and app with JIT (even though I followed your steps). Getting this error:
![image](https://user-images.githubusercontent.com/16270237/58318642-793f0980-7e18-11e9-97b3-88ff2bb0b159.png)

But if the AOT solution works, I won't care about that. Thank's again for your effort! :)

**Comment by alexej-strelzow** [comment] 2019-05-26 21:46
@MrFrankel share-loader will also work with Angular 8 and Ivy, right?
https://fireship.io/snippets/lazy-loaded-routes-angular-v8-ivy/

**Comment by MrFrankel** [comment] 2019-05-28 06:55
@alexej-strelzow I havnt tried it with Ivy yet, but share-loader is platform agnostic. it simply help expose modules outside of webpack's namespcae and allows external bundles to consume them.

As for the issues you are facing, if you can provide a repo I can look at I can try to help.

**Comment by alexej-strelzow** [comment] 2019-05-28 09:22
Thank's, just sent you an invite

**Comment by MrFrankel** [comment] 2019-05-28 13:36
@alexej-strelzow I've run your application from the repo.
The login module loads fine.
I had some issues with the reverse proxy for the post login module but once I sorted that out it worked fine as well, what am I missing?

**Comment by alexej-strelzow** [comment] 2019-05-28 14:08
@MrFrankel : ok, what you saw was the functioning JIT version. Please change to AOT in angular.json -> 
              "optimization": true,
              "outputHashing": "none",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": false,
              "vendorChunk": false,
              "buildOptimizer": true

**Comment by alexej-strelzow** [comment] 2019-05-29 10:51
@MrFrankel : sorry about the proxy, just pushed a new version. I also exported AppCommonModule in the external AppModule. Do you see the problem with AOT?

**Comment by MrFrankel** [comment] 2019-05-29 10:54
yes. im workling on it

**Comment by alexej-strelzow** [comment] 2019-05-29 10:55
@MrFrankel : thank you very much!

**Comment by MrFrankel** [comment] 2019-05-30 17:26
@alexej-strelzow  i'm still looking into this, however this does seem to work fine in the example-cli app with the same dependencies. so i'm not sure what's going on here. seems to be related to the injector scope.

**Comment by alexej-strelzow** [comment] 2019-05-30 21:28
@MrFrankel : really? When I try to build example-cli/ext-app1 with AOT (and serve main.js with simple express server), I get the following error in Console when loading ext-app1:

![image](https://user-images.githubusercontent.com/16270237/58665962-5342c900-8332-11e9-90f6-b07339b38f5a.png)

How did you resolve this? I'm not using buildOptimizer and I'm exporting AppCommonModule.
In shell-app, I've JitCompiler provided. Can you maybe push your example-cli AOT-ready version in an "aot"-branch, so I can take a look?

**Comment by MrFrankel** [comment] 2019-05-31 08:12
@alexej-strelzow I ment that the example app work with AOT disabled for the external app.
But i've also got it working with AOT enabled, ill push it in later.
It still requires a little of hard wiring, since AOT does a lot of 'magic'.

But you can get you app working with AOT I believe, ill keep working on abstracting some of the hot wiring involved.

**Comment by alexej-strelzow** [comment] 2019-05-31 14:03
@MrFrankel : I see, ok, that sounds doable (composition layer with AOT). I'm currently looking into this.  Thank's again and have a nice weekend!

**Comment by alexej-strelzow** [comment] 2019-05-31 18:12
@MrFrankel , I solved the AOT issue for the CL.
Basically I had to import polyfills.ts in main.ts and add the following two imports in polyfills.ts:
import 'core-js/es6/reflect';
import 'core-js/es7/reflect';

can't wait to have the full app working with AOT. Thank's again for pointing me in that direction!

**Comment by MrFrankel** [comment] 2019-06-02 13:07
@alexej-strelzow  i've pushed in the AOT solution, you can read in the README how to run it.
LMK if you have questions

**Comment by alexej-strelzow** [comment] 2019-06-02 17:01
@MrFrankel : thank you very much - the demo works like a charm. I'd like to integrate that in my app and try it out there. I think you have to build a new version, right? share-loader (index.js) got updated, correct?
To be able to build and integrate an (external) app into the shell app one must modify the (external) app as follows:

- update package.json: add last-call-webpack-plugin, replace-in-file-webpack-plugin, webpack-plugin-replace and update share-loader
- add extra-webpack.prod.config.js: for AOT (exposes AppModuleNgFactory)
- update angular.json: see build-ext-prod
- add main.prod.ts: there is no enableProdMode() @MrFrankel : why is that? why do we need this file?

Once I get it running in my app I'll close the issue! Thank you!

**Comment by MrFrankel** [comment] 2019-06-02 18:40
@alexej-strelzow  replace-in-file-webpack-plugin, webpack-plugin-replace  are not necessary.
you should be on share-loader latest

regarding the main.prod.ts, Angular CLI looks for `platformBrowserDynamic().bootstrapModule(AppModule)` call to traverse through the app, part of the "AOT Magic".
In order for the AOT compilation to work we need to supply it with a dummy call for platformBrowserDynamic().bootstrapModule(AppModule).

Since the application itself has already been bootstrapd by the shell-app this isn't really needed in runtime, no need for enableProdMode either as it is already set in the shell-app(CL)

Also, make sure to name you root module `AppModule` or you will have to change it in the lastcall webpacl plugin too.

LMK how it goes.

**Comment by alexej-strelzow** [comment] 2019-06-02 20:10
@MrFrankel  thank's for the explanation, I understand. Ok, meanwhile I'll install like that 
>npm i --save MrFrankel/share-loader#master

I'm getting an error during loading of main.js (pushed my code) - if I can't resolve it by tomorrow I'll let you know.

**Comment by alexej-strelzow** [comment] 2019-06-03 09:54
@MrFrankel : quick update for you. I got it working, BUT seems like sharing clarity does not work. Can you give it a look please? Login comes with its own clarity (works), basic-data relies on container -> does not work. Start both apps with "npm run serve:prod:aot", composition layer with npm run serve:prod and proxy with npm run start. Then type in something in login mask -> login -> boom

![image](https://user-images.githubusercontent.com/16270237/58793382-43f3a200-85f6-11e9-8f41-84a6c8f7f3df.png)

Another tricky detail that did const me 1 hour or 2 was that the name of the library in the webpack prod config MUST NOT be equal to the window.<variableName>, basically the library can be "foo" - does not matter, as long it's not the same name as the window-variable.

But yeah, if you could help me with the clarity sharing issue, then the bug would be 100% resolved for me. Can you please give it a look? Thank you!

**Comment by MrFrankel** [comment] 2019-06-03 10:10
can you push the updated state to your demo repo?

**Comment by alexej-strelzow** [comment] 2019-06-03 10:48
@MrFrankel : see last commit

**Comment by alexej-strelzow** [comment] 2019-06-03 15:38
@MrFrankel : fixed it, had to exclude the ngfactory:       
exclude: [/router.ngfactory/,/clr-angular.ngfactory/]

**Comment by alexej-strelzow** [comment] 2019-06-03 15:41
@MrFrankel : thank you very much for all your support - Issue is hereby closed! :)

**Comment by alexej-strelzow** [comment] 2019-06-03 15:42
@MrFrankel : would you be so kind to bump the version, so I don't have to install from the master branch? Thank you!

**Comment by alexej-strelzow** [comment] 2019-06-03 23:16
@MrFrankel : quick question. What do I have to do to be able to use chunkhash in the file name (for cache busting)? e.g. main.7e18c010a7b0ea3f4b10.js
The file gets loaded correctly, but then cannot be handled by share-loader (as it seems):
![image](https://user-images.githubusercontent.com/16270237/58840549-57d6ec80-8666-11e9-896d-04687fc8d270.png)

**Comment by amirgro** [comment] 2019-06-04 11:06
Hey @MrFrankel 
seems we are also stuck on this issue. our shell app uses AOT and we get this error once it tries to load the external app:
![image](https://user-images.githubusercontent.com/9915198/58874513-b1c0cc00-86d1-11e9-93c3-c4b25e4e42d3.png)
looks very similar to this issue here: https://github.com/angular/angular-cli/issues/8429
Any idea what were missing? Tried to look on the examples but couldn't figure out exactly whats missing.

Thanks

**Comment by alexej-strelzow** [comment] 2019-06-04 11:49
@amirgro : You are running your shell app in AOT, but your external apps in JIT. To make that work you need to provide the JIT compiler in your shell-app.

**Comment by MrFrankel** [comment] 2019-06-04 19:23
@alexej-strelzow changes were reverted in  #15.

**Comment by MrFrankel** [comment] 2019-06-04 19:25
@amirgro, like @alexej-strelzow mentioned, you can add the JIT compiler to you shell-app, this will allow you to consume the external-app that is not built using AOT.
If you want the external app to be AOT, that's a bit more tricky, I have pushed a version that supports this in the recent example-cli app in the repo.
There is also an extensive conversation regarding this in this issue.

**Comment by alexej-strelzow** [comment] 2019-06-04 19:57
@MrFrankel : you said reverted - that means that AOT is not going to work with the current version (master) ?

**Comment by MrFrankel** [comment] 2019-06-04 20:08
No, it should still work, the changes were by mistake.
I havnt released a new npm version either

**Comment by alexej-strelzow** [comment] 2019-06-04 20:23
Ok, got it. Just checked - yes - still working 👍

**Comment by alexej-strelzow** [comment] 2019-06-05 22:33
@MrFrankel : I think I still had the old version in my node_modules. The merge request https://github.com/MrFrankel/share-loader/commit/57ea1596781fc9b776598c726d3300530a262ed2

destorys my app:

![image](https://user-images.githubusercontent.com/16270237/58994943-97cada80-87f2-11e9-9705-340b49884c49.png)

when I undo the changes it works! Can you provide a fix?

**Comment by MrFrankel** [comment] 2019-06-10 06:44
@alexej-strelzow  not sure I follow, what version of share-loader is breaking you app?

**Comment by alexej-strelzow** [comment] 2019-06-10 13:30
@MrFrankel : because there is no dedicated version with the AOT fix, my project relies on the master branch -> "share-loader": "github:MrFrankel/share-loader#master"
This worked fine till commits on 04. June got into the master branch.
Starting my app with the latest changes (from 04. June) leads to the error above (see my previous post). 

I am not able to use github:MrFrankel/share-loader#master and I'm not able to use the latest version of share-loader, as 0.6.2 does not support AOT. Can you follow me? You can reproduce this on my test-project - master branch (npm run serve:prod for apps + shell and npm run start for proxy). Do I have to change something in my app to be able to run with (latest changes) github:MrFrankel/share-loader#master or is this current behavior a bug?

**Comment by MrFrankel** [comment] 2019-06-10 18:13
I haven't made any changes to the share-loader lib itself, so it shouldn't break anything.
Ill look into it and getting a fixed version out for you. sorry for the inconvenience

**Comment by alexej-strelzow** [comment] 2019-06-11 11:12
@MrFrankel : Thank's! Really appreciate your help!

**Comment by alexej-strelzow** [comment] 2019-06-16 21:05
@MrFrankel any luck with the bug?

**Comment by MrFrankel** [comment] 2019-06-17 11:07
@alexej-strelzow sorry for the delay, it's been a busy week.
I've just run the example-cli project with share-loader 0.6.2 both in the shell-app and external app and it works.
are you sure you are using share-loader@0.6.2 on all apps?

**Comment by alexej-strelzow** [comment] 2019-06-19 11:05
@MrFrankel : I changed my version to 0.6.2 and it seems to work. I guess the whole version thing was a misunderstanding. I thought the "latest" version is the master branch, because at the time you pushed the AOT example also the share-loader (index.js) changed - by mistake as I know now.

So, then I think we can resolve this issue. Thank's for this awesome library. Really appreciate that you share this with us 👍

**Closed** 2019-06-20 14:25 UTC
Labels: bug

**Comment by sai-gmbh** [comment] 2019-07-09 07:52
@MrFrankel Would you mind providing an example app with lazyloading as well

**Comment by NishanthRE** [comment] 2020-02-28 18:58
@MrFrankel Firstly your idea with the share-loader was amzing. i have some doubts. i have created a new angular 9 application into the example cli folder and included all your dependencies like extra-webpack config and changed the angular.json as we need. when triggering the build command i have stucked with the following error 
`
Generating ES5 bundles for differential loading...
An unhandled exception occurred: f:\Research & Dev\share-loader\example-cli\ext-app2\polyfills-es5.js: Invalid left-hand side in assignment expression (9:2)

   7 |          exports["polyfills-es5.js"] = factory(polyfills-es5.js);
   8 |  else
>  9 |          polyfills-es5.js = factory(polyfills-es5.js);
     |          ^
  10 | })(window, function(__WEBPACK_EXTERNAL_MODULE_f_Research_Dev_share_loader_example_cli_ext_app2_node_modules_angular_devkit_build_angular_src_angular_cli_files_models_es5_polyfills_js__) {
  11 | return /******/ (function(modules) { // webpackBootstrap
  12 | /******/         // The module cache
See "C:\Users\Admin\AppData\Local\Temp\ng-HFejQJ\angular-errors.log" for further details.`

and when i try to load the newly created application from shell app am receiving  like this
![image](https://user-images.githubusercontent.com/43135722/75578525-fd01e280-5a89-11ea-837a-54771a83f62a.png)


Can you please help me to get out from this?
