### ISSUE TITLE
Not loading with ng build --prod

### ISSUE THREAD

**Issue by sanjaypraja** [MrFrankel/share-loader#5] opened 2019-03-14 11:01 UTC
Dear Maor Frankel,

Thank you to share Angular cli project with us & it's working fine. 
We are facing one issue when we are going to deploy on production server. For production deployment we are using **ng build --prod** but it's not loading the exposing app.

**Working Case:**

For exposing app, server deployement command **npm run ng run ext-app1:build-ext**
For consumer app, server deployment command **ng build**

**Not working Case:**

For exposing app, server deployement command **npm run ng run ext-app1:build-ext**
For consumer app, server deployment command **ng build --prod**

![Screenshot from 2019-03-14 16-08-44](https://user-images.githubusercontent.com/2256488/54351794-4ccb7c00-4676-11e9-923b-516244d12e9e.png)

Can please help us how it will work with ng build --prod?

**Comment by MrFrankel** [comment] 2019-03-14 13:51
@sanjaypraja the issue is because you are running in aot mode, you can turn aot mode off in the angular.json

 "aot": false,
 "buildOptimizer": false

I am working on an AOT compatibly solution, hopefully in the next few days

**Comment by MrFrankel** [comment] 2019-03-14 14:39
it seems if you can force the JIT complier to be included in you AOT app, it will increase your bundle size for your shell app but other then that it you can benefit from all other AOT perks.

here's an example:

shell-app/app.module.ts

```
import {Compiler, COMPILER_OPTIONS, CompilerFactory, NgModule} from '@angular/core';
import {BrowserModule} from '@angular/platform-browser';
import {AppComponent} from './app.component';
import {SelectComponent} from './select.component';
import {APP_STATES} from './app.states';
import {App1Component} from './app1.component';
import {RouterModule} from '@angular/router';
import {JitCompilerFactory} from '@angular/platform-browser-dynamic';


@NgModule({
  imports: [BrowserModule,  RouterModule.forRoot(APP_STATES)],
  declarations: [AppComponent, SelectComponent, App1Component],
  bootstrap: [AppComponent],
  providers: [
    {
      provide: COMPILER_OPTIONS,
      useValue: {},
      multi: true
    },
    {
      provide: CompilerFactory,
      useClass: JitCompilerFactory,
      deps: [COMPILER_OPTIONS]
    },
    {
      provide: Compiler,
      useFactory: createCompiler,
      deps: [CompilerFactory]
    },
  ]
})

export class AppModule {
}
export function createCompiler(fn: CompilerFactory): Compiler {
  return fn.createCompiler();
}

```

**Comment by sanjaypraja** [comment] 2019-03-15 07:02
Thank you! yes, bundle size increase with JIT compiler. 
have you another way to decrease the bundle size?

**Comment by MrFrankel** [comment] 2019-03-15 07:43
Unfortunately, there is an issue with Angular lazyloading mechanism, If the loadchildren method is passed a promise, it passes it to the JIT compiler.
Hopefully they will fix this at some point. however, if you have a vendor bundle on your shell app it should be cached so it shouldn't have a significant toll on loading time and since the shell app is AOT, you will still get great performance at load time.

Can you confirm this fixed the issue so I can close this for now? ill open a issue to keep track until Angular solve this issue with loadchildren.

**Comment by sanjaypraja** [comment] 2019-03-15 08:01
issue has been resolved. Thank you!

**Comment by MrFrankel** [comment] 2019-03-15 13:31
so it seems it is possible to load an external module without the Jit Compiler, it is required to set the external module build to AOT too.
however it requires some hacking around angular bootstrapping code.

I'll add task to abstract this via an option through share-loader.

**Closed** 2019-03-15 13:31 UTC
Labels: help wanted
